name = "Dayz Modpack"
author = "oskardotglobal, Morio187"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6097e85a3c7846473f1d516762df66d7abe9ee230dd29e3a9db0b9cc737bf2e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "0.2.0"
