name = "Dayz Modpack"
author = "oskardotglobal, Morio187"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20137baf9c70ae823602a701c0e61580ff8a2107242bba22eff93247368ff1eb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "0.2.0"
