name = "Dayz Modpack"
author = "oskardotglobal, Morio187"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "215b9d40af9a8acbadc908ccf1e89ea5da3b191bb09e12c30c289a9d5c3c4744"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "0.2.0"
