name = "Dayz Modpack"
author = "oskardotglobal, Morio187"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e5e518f21c2966195b92f8b27cbfd6063d441cae4afdf4ca8a218b7a196b7f6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "0.2.0"
