[flavor_groups.client_only]
name = "Client-side exclusive mods"
description = "QOL client side mods. Selecting this is recommended."
side = "client"
choices = ["client_only_off", "client_only_on"]

[metafile.borderless-mining]
flavors = ["client_only_on"]

[metafile.nixnarrator]
flavors = ["client_only_on"]
